name: magnet_search_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  material_design_icons_flutter: ^5.0.6996
  material_floating_search_bar: ^0.3.7
  get_storage: ^2.0.3
  url_launcher: ^6.0.20
  dio_http_cache: ^0.3.0
  dio: ^4.0.4
  nb_utils: ^4.6.21
  clipboard: ^0.1.3
  dio_smart_retry: ^1.2.0
  flutter_slidable: ^2.0.0
  fluttertoast:
  filesize: 2.0.1
  simple_html_css: ^4.0.0
  dart_date: ^1.1.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  
flutter: 
  uses-material-design: true

  assets:
    - assets/